### ISSUE TITLE
broken links on Docs

### ISSUE THREAD

**Issue by DavidLeibs** [LevelOneProject/Docs#1]
There are a number of broken links on the Docs page.

 For example "Clearing Architecture Documentation" links to:
     https://github.com/LevelOneProject/Docs/blob/master/ILP/README.md

Which results in a 404

**Comment by millerabel** [comment]
Hi David, I think the team is still in process of republishing the docs and so links to docs that they haven't yet gotten to will appear broken. This should be corrected shortly as the docs are rolled out one-by-one.

**Comment by DavidLeibs** [comment]
Yea, I figured that was the case. I just wanted to make an issue so that I
could feel like a team member. 😀

**Comment by jeffplesko** [comment]
Issue resolved.  ILP and DFSP documentation has been added
